version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/transcriberapp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    versioning-strategy: increase
    groups:
      flutter-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
