name: transcriberapp
description: "A serverlass AI Audio transcriber."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # --- NEW: Serverless AI & Storage ---
  google_generative_ai: ^0.4.7   # The Gemini AI Engine
  flutter_secure_storage: ^10.3.1 # Secure Vault for API Key
  shared_preferences: ^2.5.5     # To track "First Time" launch
  url_launcher: ^6.3.2           # To open the "Get API Key" link
  
  
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  permission_handler: ^12.0.3
  path_provider: ^2.1.6
  record: ^6.2.1
  sqflite: ^2.4.3
  path: ^1.9.1
  http: ^1.6.0
  mime: ^2.0.0
  http_parser: ^4.1.2
  flutter_dotenv: ^6.0.1
  rename: ^3.1.0
  intl: ^0.20.3
  audioplayers: ^6.8.1
  share_plus: ^13.2.1
  video_player: ^2.13.0
  chewie: ^1.14.1
  google_fonts: ^8.2.0
  external_app_launcher: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"